name: bit_vector
description: A pure Dart memory-efficient packed representation for bit arrays
version: 0.4.1
author: Kwang Yul Seo <kwangyul.seo@gmail.com>
homepage: https://github.com/kseo/bit_vector

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  fixnum: ^0.10.9

dev_dependencies:
  test: ^1.3.0
